version: '3.8'

networks:
  stokei-network:
    driver: bridge

volumes:
  mysql-data:
  postgresql-data:
services:
  mysql:
    image: bitnami/mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: dev
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: stokei-api
    ports:
      - '3310:3306'
    volumes:
      - mysql-data:/bitnami/mysql/data
    networks:
      - stokei-network
