version: '3.8'

networks:
  stokei-network:
    driver: bridge

volumes:
  mysql-data:
  postgresql-data:
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: development
        DB_URL: postgresql://dev:dev@host.docker.internal:5432/stokei-api?schema=public
    container_name: api
    ports:
      - '4010:3000'
    environment:
      - DB_URL=mysql://dev:dev@mysql:3306/stokei-api
      - SERVER_HOST=api
      - SERVER_PORT=3000
      - SERVER_URL=http://api:3000
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - mysql
    networks:
      - stokei-network

  mysql:
    image: bitnami/mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: dev
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: stokei-api
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/bitnami/mysql/data
    networks:
      - stokei-network
