export enum ServerStokeiApiIdPrefix {
  ACCOUNTS = 'acc',
  ACCESSES = 'access',
  APPS = 'app',
  SITES = 'site',
  DOMAINS = 'domain',
  CURRENCIES = 'curr',
  LANGUAGES = 'lang',
  COLORS = 'color',
  PRODUCTS = 'prod',
  INVOICES = 'invoice',
  PRICES = 'price',
  PAYMENT_METHODS = 'pay_method',
  PLANS = 'plan',
  IMAGES = 'img',
  VIDEOS = 'video',
  FILES = 'file',
  VIDEO_AUTHORS = 'author',
  MODULES = 'mod',
  COURSES = 'course',
  COURSE_INSTRUCTORS = 'instructor',
  COURSE_STUDENTS = 'stud',
  SUBSCRIPTION_CONTRACTS = 'sub',
  ADDRESSES = 'address',
  PHONES = 'phone'
}
