export * from './access.entity';
export * from './account.entity';
export * from './address.entity';
export * from './app.entity';
export * from './color.entity';
export * from './course.entity';
export * from './course-instructor.entity';
export * from './course-student.entity';
export * from './currency.entity';
export * from './domain.entity';
export * from './file.entity';
export * from './image.entity';
export * from './invoice.entity';
export * from './language.entity';
export * from './module.entity';
export * from './payment-method.entity';
export * from './phone.entity';
export * from './plan.entity';
export * from './price.entity';
export * from './product.entity';
export * from './subscription-contract.entity';
export * from './video.entity';
export * from './video-author.entity';

export const Entities = [];
