export * from './access.entity';
export * from './account.entity';
export * from './address.entity';
export * from './card.entity';
export * from './cart.entity';
export * from './carts-item.entity';
export * from './classroom.entity';
export * from './classroom-instructor.entity';
export * from './classroom-module .entity';
export * from './classroom-student.entity';
export * from './color.entity';
export * from './course.entity';
export * from './courses-instructor.entity';
export * from './courses-student.entity';
export * from './currency.entity';
export * from './domain.entity';
export * from './image.entity';
export * from './language.entity';
export * from './module.entity';
export * from './modules-video.entity';
export * from './order.entity';
export * from './orders-item.entity';
export * from './payment.entity';
export * from './payments-method.entity';
export * from './phone.entity';
export * from './plan.entity';
export * from './price.entity';
export * from './product.entity';
export * from './project.entity';
export * from './subscription.entity';
export * from './video.entity';
export * from './videos-author.entity';

export const Entities = [];
