-- CreateTable
CREATE TABLE `components` (
    `id` VARCHAR(191) NOT NULL,
    `app` VARCHAR(255) NOT NULL,
    `parent` VARCHAR(255) NOT NULL,
    `type` ENUM('HEADER', 'FOOTER', 'CATALOG', 'FEATURE', 'NAVLINK', 'HERO_DEFAULT', 'HERO_WITH_VIDEO', 'HERO_WITH_IMAGE', 'HERO_WITH_IMAGE_BACKGROUND') NOT NULL,
    `data` JSON NULL,
    `updated_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` VARCHAR(255) NULL,
    `created_by` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
