name: BRANCHES

on:
  push:
    branches:
      - '**'
      - '!release/*'

  workflow_dispatch:

jobs:
  BRANCHES:
    name: BRANCHES
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Use Node.js v18.15.0
        uses: actions/setup-node@v1
        with:
          node-version: '18.15.0'

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,ts,md}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      - name: Eslint
        run: yarn lint
        env:
          CI: true

      - name: Unit tests
        run: yarn test
        env:
          PASSWORD_SECRET_KEY: ${{ env.PASSWORD_SECRET_KEY }}
          CI: true
