name: BRANCHES

on:
  push:
    branches:
      - '**'
      - '!release/*'

  workflow_dispatch:

env:
  NODE_VERSION: '18.15.0'

jobs:
  BRANCHES:
    name: BRANCHES
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18.15.0
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,ts,md}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Eslint
        run: yarn lint

      - name: Unit tests
        run: yarn test
        env:
          PASSWORD_SECRET_KEY: ${{ env.PASSWORD_SECRET_KEY }}
