on:
  # The issues event below is only needed for the default (auto) mode,
  # you can remove it otherwise
  issues:
    types: [assigned]
  # The issue_comment event below is only needed for the ChatOps mode,
  # you can remove it otherwise
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          gitSafeReplacementChar: '-'
          openPR: true
          autoCloseIssue: true
          copyIssueDescriptionToPR: true
          copyIssueLabelsToPR: true
          copyIssueAssigneeToPR: true
          copyIssueProjectsToPR: true
          copyIssueMilestoneToPR: true
          commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
          branchName: '${issue.number}-${issue.title[0,64],}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
