name: CI_CD

on:
  release:
    types: [published]

env:
  IMAGE_NAME: stokei-api
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  CI_CD:
    name: CI_CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Getting version
        id: versions-variables
        run: |
          echo ::set-output name=VERSION_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=VERSION_NUMBER::$(echo $GITHUB_REF | cut -d / -f 3 | awk '{sub(/v/,"")}1')

      - name: Check output version
        env:
          RELEASE_VERSION: ${{ steps.versions-variables.outputs.VERSION_NAME }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.versions-variables.outputs.VERSION_NUMBER }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.versions-variables.outputs.VERSION_NAME }}
